<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventorySystem.Data\InventorySystem.Data.csproj" />
    <ProjectReference Include="..\InventorySystem.Repository\InventorySystem.Repository.csproj" />
  </ItemGroup>

</Project>
